apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod
spec:
  serviceAccountName: identity-sa
  containers:
  - name: sample
    image: amazon/aws-cli
    command: 
      - aws
      - ecr
      - list-images
      - --repository-name
      - my-ecr-repo
  restartPolicy: Never
